# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Bootstrap configuration with the profiler runtime enabled. Use this when you
# need coverage support (`libprofiler_builtins`) in the sysroot.

change-id = "ignore"
profile = "dist"

[build]
extended = true
profiler = true

[install]
prefix = ""

[llvm]
download-ci-llvm = false

[gcc]
download-ci-gcc = false

[rust]
download-rustc = false
